
name: BuildAndPush

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:    
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v2

      - name: Gradle Build Action        
        uses: gradle/gradle-build-action@v2.1.0
